POST http://127.0.0.1:8080/v1/user
Content-Type: application/json

{
    "id":"1",
    "username":"小小展玮14",
    "password":"asdf"
}

###get method
GET http://127.0.0.1:8080/v1/user

###delete method
DELETE  http://127.0.0.1:8080/v1/user/0

###login method GET
GET http://127.0.0.1:8080/v1/user/login?username=小小展玮1&password=asdf

###删库跑路
GET http://127.0.0.1:8080/v1/user/deleteall